# fly.toml app configuration file generated for me-withered-bird-1472 on 2025-01-22T11:39:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'me-withered-bird-1472'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
